### ISSUE TITLE
Interpretation of results

### ISSUE THREAD

**Issue by kexinzhengn** [jiatiansun/Eventfulness#2]
Hi. Thank you for sharing the code of such a wonderful project. 

I tried running the pretrained model on my video and get a T X 13 matrix. I wonder which dimension is the 'marginal eventfulness'? I also wants to ask how do you normalize the signal for visualization.

Thanks.

**Comment by jiatiansun** [comment]
Hi, sorry for the delay in response. I have been contacting other authors of the paper to confirm the answers to some of your questions. The first dimension is marginal eventfulness. As for visualization, we normalize each signal by zero-meaning it and rescaling the variance to be 1. We expect to release the visualization GUI and all other analysis code by sometime around June, so evaluation and usage of our model should be much easier then.

**Comment by kexinzhengn** [comment]
> Hi, sorry for the delay in response. I have been contacting other authors of the paper to confirm the answers to some of your questions. The first dimension is marginal eventfulness. As for visualization, we normalize each signal by zero-meaning it and rescaling the variance to be 1. We expect to release the visualization GUI and all other analysis code by sometime around June, so evaluation and usage of our model should be much easier then.

Thank you for the reply. It does help me understand the output better. Looking forward to the release of GUI code :)
