### ISSUE TITLE
Prediction for a single video

### ISSUE THREAD

**Issue by dodoxxb** [jiatiansun/Eventfulness#3]
Thank you for your wonderful work and I would like to ask how to make predictions on a single video using a pre-trained model. The ckpt model published on the website does not seem to work. Thanks a lot.

**Comment by jiatiansun** [comment]
Would you mind sending me the error you get? and describing the exact way that the model failed to work. (Also make sure beforehand that you are running the code on a system with Nvidia gpu)

**Comment by dodoxxb** [comment]
Thank you very much for your answer. I have successfully configured the pre-trained model for inference on a private dataset. Wonderful work. Thank you.
